/****************************************************************************************

	Purpose:		Defines the output values of functors.

	Author:			David Wei
	Date:			2/19/15
	Last Modified:	Initial Revision
	IDE USED:		gcc version 4.8.3 (cygwin64 on Windows 8.1)

****************************************************************************************/

#ifndef FUNCTOROUTPUTS_INC
#define FUNCTOROUTPUTS_INC

//***************************************************************************************
// Functor Output Definitions
//***************************************************************************************

const short LESS_THAN       = -1;
const short EQUALS          =  0;
const short GREATER_THAN    =  1;

#endif

